# Generated by Django 4.1.3 on 2022-11-24 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 24, 11, 7, 55, 764231, tzinfo=datetime.timezone.utc))),
                ('motif', models.CharField(blank=True, max_length=100, null=True)),
                ('justification', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Abscence',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Adress',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('students_number', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('F_Class', 'first class'), ('S_Class', 'second class'), ('T_Class', 'third class')], default='F_Class', max_length=10)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(choices=[('F_Class', 'first class'), ('S_Class', 'second class'), ('T_Class', 'third class')], default='F_Class', max_length=10)),
                ('typeModule', models.CharField(choices=[('O_Module', 'optional module'), ('R_Module', 'required module')], default='O_Module', max_length=10)),
                ('group', models.ManyToManyField(to='university_app.group')),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('familyName', models.CharField(max_length=100)),
                ('birthDate', models.DateField(default=datetime.date(2004, 1, 1))),
                ('email', models.EmailField(max_length=60, verbose_name='email ')),
                ('grade', models.CharField(default=0, max_length=200)),
                ('emailWork', models.EmailField(max_length=60)),
                ('due', models.FloatField(default=0)),
                ('photo', models.ImageField(max_length=200, upload_to='photos/Teacher')),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='TeachModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberHoursTeach', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveIntegerField(default=2022)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('familyName', models.CharField(max_length=100)),
                ('birthDate', models.DateField(default=datetime.date(2004, 1, 1))),
                ('email', models.EmailField(max_length=60, verbose_name='email ')),
                ('photo', models.ImageField(max_length=200, upload_to='photos/students')),
                ('state', models.CharField(max_length=50)),
                ('situation', models.CharField(max_length=50)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_app.address')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_app.group')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('classrommNumber', models.IntegerField()),
                ('goal', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('listTools', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Run', 'Running'), ('Achive', 'Achieved'), ('Cancel', 'Canceled'), ('Delay', 'Delayed')], default='Run', max_length=50)),
                ('type', models.CharField(choices=[('nrml', 'Normal'), ('catchup', 'Catching-up'), ('support', 'Support'), ('train', 'Training')], default='nrml', max_length=50)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university_app.module')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='teacher',
            field=models.ManyToManyField(through='university_app.TeachModule', to='university_app.teacher'),
        ),
    ]
